// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMwnSdZqb9EEnTrTTSXgXfmWdjah-1WIs',
    appId: '1:1034166298509:android:f3d56ce8b6f299b3f63fc4',
    messagingSenderId: '1034166298509',
    projectId: 'slrsharemap',
    storageBucket: 'slrsharemap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHEhK3CL5iBv6oraLLWzpBntlkGfKpPyA',
    appId: '1:1034166298509:ios:69fe4d4a3dfa1903f63fc4',
    messagingSenderId: '1034166298509',
    projectId: 'slrsharemap',
    storageBucket: 'slrsharemap.appspot.com',
    iosClientId: '1034166298509-l31280onm3ctf08lm3qcjudrqcige10o.apps.googleusercontent.com',
    iosBundleId: 'powerd.uetomo.slrSha',
  );
}
